service: web-gis-api
runtime: python39
entrypoint: gunicorn -b :$PORT web_gis_api:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  BUCKET_NAME: "web-gis-2198" 